# Generated by Django 5.2.5 on 2025-08-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateTimeField(auto_created=True)),
                ('shopweb_name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('shelf', models.CharField(max_length=200)),
            ],
        ),
    ]
