# Generated by Django 5.2.5 on 2025-08-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Shops',
        ),
        migrations.RenameField(
            model_name='shops',
            old_name='shopweb_name',
            new_name='shop_name',
        ),
    ]
