# Generated by Django 5.2.5 on 2025-08-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_blogs_shops_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shops',
            old_name='content',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='shops',
            old_name='shelf',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='shops',
            old_name='shop_name',
            new_name='shelf_number',
        ),
        migrations.AlterField(
            model_name='shops',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
