# Generated by Django 5.2.5 on 2025-08-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_content_shops_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
