# Generated by Django 5.2.5 on 2025-08-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_shops_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shops',
            old_name='customer_name',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='shops',
            old_name='product_name',
            new_name='shelf',
        ),
        migrations.RenameField(
            model_name='shops',
            old_name='shelf_number',
            new_name='shop_name',
        ),
        migrations.AlterField(
            model_name='shops',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
