# Generated by Django 5.2.5 on 2025-08-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_customer_name_shops_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shops',
            old_name='content',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='shops',
            old_name='shelf',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='shops',
            old_name='shop_name',
            new_name='shelf_number',
        ),
    ]
